# Partner Level Information
title = "Labrys"
website="https://labrys.io/"

# Partner company details
registered_company_name = ""
registered_company_address = ""
company_registration_number = ""
company_representative_name = ""
company_representative_email = ""
company_poc_name = ""
company_poc_email = ""

# Partner Directory details
logo="https://labrys.io/wp-content/uploads/2024/03/logo-1.svg"
brand_hex="#00FFA7"
description="Labrys is the largest web3 consulting and development agency in Australia. We work with clients to plan, design, build and deploy custom web3 solutions"
discord=""
twitter="https://twitter.com/Labrys_io"
region_focus=[APAC/NA/EMEA]
service_category= [Web3 Development]

# Partner service details
detailed_overview_of_services=""
strengths=""
weaknesses=""
projects=""
price_range=""
get_in_touch_process=""
get_in_touch_email=""
get_in_touch_telegram=""
get_in_touch_phone=""
get_in_touch_calendly=""
other_details=""